# Generated by Django 4.2.17 on 2025-01-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_rating_rating_rating_rating_between_1___10'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='edited_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='edited_at',
            field=models.DateField(auto_now=True),
        ),
    ]
