# Generated by Django 4.2.17 on 2024-12-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product_category',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='unique_product_category'),
        ),
    ]
