# Generated by Django 4.2.17 on 2024-12-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_purchase_discount_purchase_price_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.product'),
        ),
    ]
